version: '3'
services:
    rasa:
      container_name: "rasa_server"
      user: root
      build: 
        context:  .
      volumes:
      - "./:/app"
      ports: 
        - "5005:5005"
    duckling:
      image: 'rasa/duckling:latest'
      container_name: duckling
      restart: always
      ports:
        - '8002:8002'
